# Generated by Django 5.0.1 on 2024-01-25 12:01

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.TextField(max_length=200)),
                ('company_email', models.EmailField(max_length=254)),
                ('company_address', models.TextField(blank=True, max_length=200)),
                ('company_country', django_countries.fields.CountryField(max_length=2)),
                ('company_iban', models.TextField(blank=True, max_length=50)),
                ('company_id', models.TextField(blank=True, max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
