# Generated by Django 5.0.1 on 2024-01-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_alter_company_profile_company_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_profile',
            name='company_name',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
