# Generated by Django 5.0.1 on 2024-01-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_alter_company_profile_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_profile',
            name='company_name',
            field=models.TextField(default='My company', max_length=200),
        ),
    ]
