# Generated by Django 5.0.1 on 2024-01-30 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_alter_company_profile_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_profile',
            name='company_logo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
