# Generated by Django 5.0.1 on 2024-02-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_alter_company_profile_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_profile',
            name='company_logo',
            field=models.ImageField(default='default.svg', upload_to='company_logo'),
        ),
    ]
