# Generated by Django 5.1.6 on 2025-06-03 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0008_alter_company_profile_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_profile',
            name='company_country',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
