# Generated by Django 5.1.6 on 2025-06-03 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0002_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='c_country',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
